### ISSUE TITLE
Failed to build iOS app

### ISSUE THREAD

**Issue by GinGod** [fluttercandies/flutter_bdface_collect#37]
### Content

克隆项目后直接运行报错, 运行日志: 

aunching lib/main.dart on iPhone 14 Pro in debug mode...
Adding input path to Thin Binary build phase.
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Running pod install...
Running Xcode build...
Xcode build done.                                           47.7s
Failed to build iOS app
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FaceSDKManager

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_IDLFaceDetectionManager

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_IDLFaceLivenessManager

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.

**Comment by GinGod** [comment]
macOS Monterey 版本 12.6.6
XCode 14.2
cocoapods 1.12.1
运行demo软件 Android Studio

**Comment by CyJaySong** [comment]
百度的SDK不支持在虚拟机运行

**Comment by sunjiaming** [comment]
在flutter中 如何条件编译，让百度sdk在模拟器下不参与编译呢

**Comment by git-boya** [comment]
> 在flutter中 如何条件编译，让百度sdk在模拟器下不参与编译呢

@sunjiaming  请问有解决办法了吗?

**Comment by CyJaySong** [comment]
虚拟机调试的时候用这个
```
  flutter_bdface_collect:
    git:
      url: https://github.com/fluttercandies/flutter_bdface_collect.git
      ref: 487b1486cffdb66c68d6c9fb04c0a46ba1bb8a21
```
